# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e2520a7904066ef6753396512a1be65139ae3b3ac3b610e8028c1c460d45f91e3f9c0440014c9dc006a08e2cbd2f1a4af450eef47d2c67450a238785c5114e20

test:
  secret_key_base: 86a7bf5a50ddcd112130ea807a177a71f6abc15972e960e22378cfc5f64ebe811117786b245caf4700c4e1506e87214e55cea844221edf1a243fea688943d740

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
