# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f127ca04f5036bc6e6c875e441a4abf151b177917ffa032f94c876eb4fea954aadbae97b3609cb862165e5238dfe06a0a0d908fd3787656da1c95ae7b644f066

test:
  secret_key_base: 0b38305d196e1998bd3070fd5a3f619b14353cc7841ed9b91a3e59e6a1e0f2ece9e30a0d69fbad09861026ed256071c0c27e95b00abaf326142ada7092c0565c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
